<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-26G0JUG" failures="2" tests="16" name="com.Reporting.tests.LoanSample" time="590.974" errors="0" timestamp="2024-05-22T17:42:52 IST" skipped="0">
  <testcase classname="com.Reporting.tests.LoanSample" name="validatePaymentAndReceiptColumns" time="52.261"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.LoanSample" name="validateCashBalanceForReceipt" time="95.188"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.LoanSample" name="validateCashBalanceForPayments" time="65.379"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.LoanSample" name="validateSortingOfCashBalanceTable" time="14.605"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.LoanSample" name="validateCashBalanceValueInTopRowOfCashBalanceTable" time="61.504">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Reporting.tests.LoanSample.validateCashBalanceValueInTopRowOfCashBalanceTable(LoanSample.java:509)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateCashBalanceValueInTopRowOfCashBalanceTable -->
  <system-out/>
  <testcase classname="com.Reporting.tests.LoanSample" name="validateLoanAccountSectionsVisibility" time="18.271"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.LoanSample" name="validateCurrentLoanBalance" time="18.553"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.LoanSample" name="validateLoanAccountTabTableColumns" time="14.835"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.LoanSample" name="validateDefaultSortOrderOfCashBalanceTable" time="14.285"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.LoanSample" name="validateLoanBalanceAmount" time="29.585"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.LoanSample" name="validateLoanBalanceValueInTopRowOfCashBalanceTable" time="48.970"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.LoanSample" name="validateFundingAccountSectionsVisibility" time="18.226"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.LoanSample" name="validateCurrentAllocatedAmount" time="16.578"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.LoanSample" name="validateFundingAccountTabTableColumns" time="29.886"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.LoanSample" name="validateReverseChronologicalOrderOfCashBalanceTable" time="31.373"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.LoanSample" name="validateAllocatedAmountValueInTopRowOfCashBalanceTable" time="61.475">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Reporting.tests.LoanSample.validateAllocatedAmountValueInTopRowOfCashBalanceTable(LoanSample.java:1469)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateAllocatedAmountValueInTopRowOfCashBalanceTable -->
  <system-out/>
</testsuite> <!-- com.Reporting.tests.LoanSample -->
