<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-26G0JUG" failures="1" tests="7" name="com.Loans.NewLoan.tests.NewLoanTest2" time="225.216" errors="0" timestamp="2024-03-07T17:34:43 IST" skipped="0">
  <testcase classname="com.Loans.NewLoan.tests.NewLoanTest2" name="validateLoanStatusLive" time="32.433"/>
  <system-out/>
  <testcase classname="com.Loans.NewLoan.tests.NewLoanTest2" name="validateLoanStatusOverdue" time="23.992"/>
  <system-out/>
  <testcase classname="com.Loans.NewLoan.tests.NewLoanTest2" name="validatePaymentDateInLoanHistory" time="8.830"/>
  <system-out/>
  <testcase classname="com.Loans.NewLoan.tests.NewLoanTest2" name="validateCashflowTab" time="10.846"/>
  <system-out/>
  <testcase classname="com.Loans.NewLoan.tests.NewLoanTest2" name="validateCurrentAmountAfterDisbursement" time="45.398"/>
  <system-out/>
  <testcase classname="com.Loans.NewLoan.tests.NewLoanTest2" name="validateCurrentAmountAfterRepayment" time="41.133"/>
  <system-out/>
  <testcase classname="com.Loans.NewLoan.tests.NewLoanTest2" name="validateNotRepaidLoans" time="62.584">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Loans.NewLoan.tests.NewLoanTest2.validateNotRepaidLoans(NewLoanTest2.java:661)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateNotRepaidLoans -->
  <system-out/>
</testsuite> <!-- com.Loans.NewLoan.tests.NewLoanTest2 -->
